# Generated by Django 2.1.1 on 2019-04-06 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toyshare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='renting',
            name='toy_id_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='toy1', to='toyshare.Toy'),
        ),
    ]
